SELECT ID_USUARIO,
       ID_ENDER_USUARIO,
       NM_CIDADE, 
       NM_BAIRRO 
FROM       T_BAZE_ENDER_USUARIO
    WHERE DS_COMPLEMENTO IS NULL
        ORDER BY ID_USUARIO, NM_USUARIO;

SELECT U.ID_USUARIO,
       U.NM_USUARIO,
       U.NR_PESO,
       B.NR_PESO
FROM        T_BAZE_USUARIO       U
    INNER JOIN  T_BAZE_BIKE   B   ON (U.ID_USUARIO = B.ID_USUARIO)
        WHERE B.NR_PESO = 'P' AND U.NR_PESO > 60
            ORDER BY U.ID_USUARIO, U.NM_USUARIO;

SELECT U.ID_USUARIO,
       U.NM_USUARIO,
       MAX(B.NR_QUADRO) MAIOR_QUADRO,
       MIN(B.NR_QUADRO) MENOR_QUADRO,
       MAX(B.NR_MARCHA) MAIOR_MARCHA,
       MIN(B.NR_MARCHA) MENOR_MARCHA
FROM       T_BAZE_USUARIO    U    INNER JOIN    T_BAZE_BIKE    B
    ON (U.ID_USUARIO = B.ID_USUARIO)
        WHERE U.ID_USUARIO = 1 OR U.ID_USUARIO = 2 OR U.ID_USUARIO = 3
            GROUP BY U.ID_USUARIO, U.NM_USUARIO;

SELECT U.ID_USUARIO,
       U.NM_USUARIO,
       MAX(C.NR_TEMPO) MAIOR_TEMPO,
       MIN(C.NR_TEMPO) MENOR_TEMPO,
       AVG(C.NR_TEMPO) MEDIA_TEMPO,
       MAX(C.NR_KM)    MAIOR_DISTANCIA,
       MIN(C.NR_KM)    MENOR_DISTANCIA,
       AVG(C.NR_KM)    MEDIA_DISTANCIA
FROM       T_BAZE_USUARIO   U   INNER JOIN   T_BAZE_CORRIDA   C
    ON (U.ID_USUARIO = C.ID_USUARIO)
        WHERE U.ID_USUARIO = 1 OR U.ID_USUARIO = 2 OR U.ID_USUARIO = 3  
            GROUP BY U.ID_USUARIO, U.NM_USUARIO
                HAVING MAX(C.NR_KM) > 21 AND MAX(C.NR_TEMPO) > 88;      

  
       

       